import type { Metadata } from 'next'
import Script from 'next/script'
import './globals.css'
import { Popup18, CookieConsent } from '@/components/Popups'

export const metadata: Metadata = {
  title: { default: 'VipAcompanhante', template: '%s | VipAcompanhante' },
  description: 'A maior plataforma de acompanhantes do Brasil.',
  // OpenGraph - usado pelo WhatsApp, Facebook, etc
  openGraph: {
    type: 'website',
    locale: 'pt_BR',
    url: 'https://www.vipacompanhante.com',
    siteName: 'VipAcompanhante',
    title: 'VipAcompanhante',
    description: 'A maior plataforma de acompanhantes do Brasil.',
    images: [
      {
        url: 'https://www.vipacompanhante.com/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'VipAcompanhante',
      },
    ],
  },
  // Twitter Card
  twitter: {
    card: 'summary_large_image',
    title: 'VipAcompanhante',
    description: 'A maior plataforma de acompanhantes do Brasil.',
    images: ['https://www.vipacompanhante.com/og-image.jpg'],
  },
  // Remove o "Generated by Next.js"
  generator: '',
  applicationName: 'VipAcompanhante',
}

// Schema Markup para SEO
const schemaOrganization = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'VipAcompanhante',
  url: 'https://www.vipacompanhante.com',
  logo: 'https://www.vipacompanhante.com/logo.png',
  description: 'A maior plataforma de acompanhantes do Brasil.',
  sameAs: []
}

const schemaWebsite = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'VipAcompanhante',
  url: 'https://www.vipacompanhante.com',
  potentialAction: {
    '@type': 'SearchAction',
    target: 'https://www.vipacompanhante.com/buscar?q={search_term_string}',
    'query-input': 'required name=search_term_string'
  }
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <head>
        <meta name="google-site-verification" content="wHXM3mWwBaA2UUFVE_KknzGKypmW4R_ZF13fLoqtAKs" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaOrganization) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaWebsite) }}
        />
      </head>
      <body>
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-0QY66R3RKB"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-0QY66R3RKB');
          `}
        </Script>
        
        <Popup18 />
        <CookieConsent />
        {children}
      </body>
    </html>
  )
}